<style>
html {
    display: table;
    height: 100%;
    width: 100%;
}

body {
    background: #e74c3c;
    font-family: arial;
    display: table-cell;
    vertical-align: middle;
    text-align: center;

    color: white;
}

</style>
<html lang="cs-cz">
	<head>
		<meta charset="utf-8" />
        <title>Stránka nenalezena</title>
	</head>
    <body>
		<h1>Vámi hledaná stránka nebyla nalezena.</h1>
        <a href="<?= URL_ROOT ?>/">Přejděte na hlavní stránku.</a>
    </body>
</html>