<!-- Úspěšný import otázek.. -->
<h3 style="margin-top: 0; text-align: center;">Otázky úspěšně importovány</h3>
<p>Do aplikace bylo úspěšně vloženo <span class="label label-success"><?= $newCount ?></span> otázek.
 Celkem jich tedy je <span class="label label-primary"><?= $total ?></span>, z nichž <span class="label label-primary"><?= $notUsed ?></span> je ještě nepoužitých. Více informací o stavu otázek se dozvíte ve správě otázek (odkaz na tlačítku níže).</p>
<p class="text-success">Import úspěšně dokončen ;)</p>
<a class="btn btn-primary btn-sm" href="<?= URL_ROOT ?>/admin/">Na hlavní stránku</a>
<a class="btn btn-primary btn-sm" href="<?= URL_ROOT ?>/admin/questions/">Správa otázek</a>