<!DOCTYPE html>
<html>

	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="">
		<meta name="author" content="">

		<title><?= isset($title) ? $title . ' - ' : null ?>Otázky a odpovědi</title>

		<!-- JQUERY -->
		<script src="<?= URL_ROOT ?>/media/js/jquery.js"></script>

		<!-- BOOTSTRAP -->
		<link href="<?= URL_ROOT ?>/media/bootstrap/bootstrap.min.css" rel="stylesheet">
		<script src="<?= URL_ROOT ?>/media/bootstrap/bootstrap.min.js"></script>

		<!-- jQuery form -->
		<script src="<?= URL_ROOT ?>/media/js/jquery.form.js"></script>

		<!-- TABLESORTER -->
		<script src="<?= URL_ROOT ?>/media/tablesorter/jquery.tablesorter.min.js"></script>
		<link href="<?= URL_ROOT ?>/media/tablesorter/style.css" rel="stylesheet">
		<style type="text/css">.souhrn{display: none;}</style>

		<!-- VLASTNÍ -->
		<link href="<?= URL_ROOT ?>/media/css/admin.css" rel="stylesheet">
		<script src="<?= URL_ROOT ?>/media/js/admin.js"></script>
	</head>

	<body>
		<!-- Navigation -->
		<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
			<div class="container">
				<!-- Brand and toggle get grouped for better mobile display -->
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
						<span class="sr-only"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="<?= URL_ROOT ?>/admin/">Otázky a odpovědi</a>
				</div>
				<!-- Collect the nav links, forms, and other content for toggling -->
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav">
						<li>
							<a href="<?= URL_ROOT ?>/admin/">Nastavení hry</a>
						</li>
						<li style="font-style: italic;"><a>Souboj dvou týmů odpovídáním na otázky různých kategorií a obtížnosti z herního pole.</a></li>
					</ul>
				</div>
				<!-- /.navbar-collapse -->
			</div>
			<!-- /.container -->
		</nav>

		<div class="container">

			<!-- Hlášky a zprávy -->

<?php $this->echoMessages() ?>

			<!-- /Hlášky a zprávy -->


			<!-- Obsah stránky -->

<?php $this->run(TRUE); ?>

			<!-- /Obsah stránky -->

			<!-- Footer -->
			<hr>
			<footer>
				<div class="row">
					<div class="col-lg-12">
						<p>Aplikace vytvořená pro Gymnázium v Třinci. Copyright &copy; 2015.</p>
					</div>
				</div>
			</footer>
			<!-- /Footer -->

		</div>
	</body>

</html>
